message: Config Server Refresh Test from user application
spring.rabbitmq.host: 104.43.141.31
spring.rabbitmq.port: 5672
spring.rabbitmq.username: admin
spring.rabbitmq.password: admin
ccop.rabbitmq.queue: ccop.queue
ccop.rabbitmq.exchange: ccop.direct
ccop.rabbitmq.routingkey: ccop.routingkey
socview.rabbitmq.queue: socview.queue.outbound
socview.rabbitmq.exchange: socview.direct
socview.rabbitmq.routingkey: socview.routingkey
logs.rabbitmq.queue: logs.queue
logs.rabbitmq.exchange: logs.direct
logs.rabbitmq.routingkey: logs.routingkey
smclogs.rabbitmq.queue: smclogs.queue
smclogs.rabbitmq.exchange: smclogs.direct
smclogs.rabbitmq.routingkey: smclogs.routingkey
